### ISSUE TITLE
Maven plugin: diktat should have it's own maven plugin

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#261]
Describe functionality and prepare a POC

**Comment by petertrr** [comment]
Plugin should let:
* Set config file location
* Have a task to generate config (basically, copy default config file from inside the jar to working directory)
* ...

**Comment by petertrr** [comment]
Another drawback of current implementation via antrun is [from here](https://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html): 'Requires dependency resolution of artifacts in scope: test'. The dedicated plugin should not need any of project dependencies in order to only analyze source code.
