### ISSUE TITLE
Conditionals should be allowed to not be wrapped in braces if they complete in single line

### ISSUE THREAD

**Issue by Animeshz** [cqfn/diKTat#472]
## Describe the bug
When conditionals `if (condition) <>`, or `if (condition) <> else if (condition2) <> else <>` ends in single line, it is not allowed to have no braces.

## Expected behavior
It should be allowed have no braces.

## Observed behavior
Following lint error is thrown:
```kotlin
[NO_BRACES_IN_CONDITIONALS_AND_LOOPS] in if, else, when, for, do, and while statements braces should be used. Exception: single line if statement.: IF
````

## Steps to Reproduce
1. Copy the following reproducible code:
```kotlin
fun <E> test(collection: Collection<E>) {
    if (collection.isEmpty()) return

    // ...
}

fun test2(number: Int) {
    if (number < 0) throw Exception()
}
```
2. Run the diktat linter with default configurations.

## Environment information
* diktat version: **0.1.2**
* build tool (maven/gradle): **gradle**
* how is diktat run (CLI, plugin, etc.): **gradle task**
* kotlin version: **1.4.10**
* operating system: **Windows 10 Build 1909**
* link to a project (if your project is public): -

**Comment by petertrr** [comment]
Diktat currently allows single-line conditional only with two branches: `if (condition) foo() else bar()` is valid code. This is written in [code style](https://github.com/cqfn/diKTat/blob/master/info/diktat-kotlin-coding-style-guide-en.md#rule-33-braces-must-be-used-in-conditional-statements-and-loop-blocks).
@akuleshov7 could you comment, should we support single-line conditional with more than two branches or it is by design of our code style?

**Comment by akuleshov7** [comment]
@Animeshz actually this is behavior is correct. We want to force programmers to have braces `{}` in all if statements.
The only exception is ternary `if () else ` statement where it should not be used due to compactness.
