### ISSUE TITLE
WRONG_NEWLINES autofix is breaking the code

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#903]
``` 
   fun getAllTestConfigs(): List<TestConfig> {
        return listOf(this) + this.childConfigs.flatMap { it.getAllTestConfigs() }
    }
```

will change to the following:
```
    fun getAllTestConfigs() = listOf(this) + this.childConfigs.flatMap { it.getAllTestConfigs() }
```

and it won't compile, because it is a bug in Kotlin and Kotlin is not able to understand a type with a recursive call 

[WRONG_NEWLINES] incorrect line breaking: functions with single return statement should be simpl
ified to expression body

The hack is easy - we should avoid this fix for recursive calls

:D :D :D

**Comment by akuleshov7** [comment]
@Cheshiriks this is a good example for the scientific paper

**Comment by petertrr** [comment]
@akuleshov7 I don't think it's a bug in Kotlin, because the compiler can't determine a definite type in this case. It could be any supertype of `List<TestConfig>`, e.g. `getAllTestConfigs` could return `Any`, and this example would compile. And since the expects a specific type, it marks it as an error.
