### ISSUE TITLE
NPE in LONG_LINE rule on Binary Expressions

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/diKTat#920]
The file: RxKotlin/src/main/kotlin/io/reactivex/rxjava3/kotlin/Observables.kt from https://github.com/ReactiveX/RxKotlin

fails due to Binary Expression (String Concatenation) with 

```

[ERROR] 2021-06-10 16:34:37 Internal error has occurred in rule [line-length]. Please make an issue on this bug at https://github.com/cqfn/diKTat/.
                       As a workaround you can disable these inspections in yml config: <[LONG_LINE]>.
                       Root cause of the problem is in [/mnt/d/RxKotlin/src/main/kotlin/io/reactivex/rxjava3/kotlin/Observables.kt] file.
                       Node, where the problem appeared:
                       kotlin.FILE: "@file:Suppress("unused", "HasPlatformType")

java.lang.NullPointerException
        at org.cqfn.diktat.ruleset.rules.chapter3.LineLength.fixBinaryExpression(LineLength.kt:252)
        at org.cqfn.diktat.ruleset.rules.chapter3.LineLength.fixError(LineLength.kt:233)

```

**Comment by kgevorkyan** [comment]
#### The reason of the bug.
NPE exception appeared on the following block in RxKotlin project:
```kotlin
@Deprecated("New type inference algorithm in Kotlin 1.4 makes this method obsolete. Method will be removed in future RxKotlin release.",
    replaceWith = ReplaceWith("Observable.combineLatest(source1, source2, source3, source4, combineFunction)", "io.reactivex.Observable"),
```
at the line with `ReplaceWith` function call.

The reason was that in `checkStringTemplate()` we had condition `if (difference > node.text.length)`, \
which was true in this case, but we have no any `OPERATION_REFERENCE`, therefore `fixBinaryExpression()` throwed exception.

#### How it could be and why.
It seems, that condition `if (difference > node.text.length)` was just a workaround for string templates, which already contain `+`
```kotlin
    val longStringExpression = "First part" + "second Part"
```
so in such string `"second part"` should be moved to the next line (in case of corresponding limit).
And it worked fine just because of we had another bug - previously we incorrectly identified node, which across the limit.

In our tests `LongLineRValueTest.kt`, the symbol `c` from `"second Part"` was on the limit, but by `node.psi.findElementAt()` from `checkLength()` we figured out, that `"First part"` is incorrect node (it was bug), so the `difference > node.text.length` for it is `true`.\
However, such condition should be `false` in any case: **the part of the string, which located to the left of the limit couldn't be greater, than the whole string size**. Moreover, there wasn't any check, that such node really contain `OPERATION_REFERENCE`.

**Reason**: Previously, we didn't consider that `offset`, which used for `node.psi.findElementAt()` is changes in course of fixing, so we take incorrect nodes.

The same situation appeared in RxKotlin, but in this case we have no `+`, so we get NPE.
